name:                ParserRecovery
version:             0.1.0.0
github:              "mattysmith22/ParserRecovery"
license:             BSD3
author:              "Matthew Smith"
maintainer:          "mattysmith22@googlemail.com"
copyright:           "2020 Matthew Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Investigation of error-recovery in monadic parser combinator libraries

dependencies:
- base >= 4.7 && < 5
- mtl == 2.2.2

library:
  source-dirs: src

executables:
  ParserRecovery-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParserRecovery

tests:
  ParserRecovery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParserRecovery
